### PR TITLE
After dinner improve-mints

### PR DESCRIPTION
**Pull request by nexdrew**
Just some minor updates:
- Commit 53ef2cc - Update explicit dependency versions to latest
- Commit 44c9cb1 - Wrap output of npm/github/twitter user links with conditionals (fixes incorrect links for Emily)
- Commit fa0836a - Update Node versions to test with in Travis

### CODE REVIEW

**Comment by aredridel** [comment]
Hm. Should continue testing with node 0.10 for the time being since that's what the website uses (for ... not too much longer now!)

**Comment by nexdrew** [comment]
@aredridel Good point; I didn't realize this. I'll add 0.10 back. Thanks!

**Comment by aredridel** [comment]
Thank you!

**Comment by aredridel** [comment]
Shiny!

**Comment by aredridel** [comment]
Want to `npm version minor` and `npm publish` that?

**Comment by nexdrew** [comment]
@aredridel Will do, thanks!

**Comment by aredridel** [comment]
Sweet. After that, a PR to newww with a version bump to `^thatversion` for humans, and you can deploy to production!

**Comment by nexdrew** [comment]
Shoot, just realized my attempt to update `tap` to latest didn't quite grab the latest version. :disappointed: Guess it only grabbed the latest version that was compatible with previous semver range. Same for `handlebars`. Oh well, moving on...

**Pull request merged**
