### PR TITLE
Add Nicole

### PR DESCRIPTION
**Pull request by stubbornella**

### CODE REVIEW

**Comment by bcoe** [comment]
\o/ welcome!

**Comment by stubbornella** [comment]
Thanks! Ok to merge @bcoe?

**Comment by stubbornella** [comment]
Oh, and is it intentional to have a separate commit that bumps the version number? Based on comments by @nexdrew, here: https://github.com/npm/humans/pull/29

**Comment by bcoe** [comment]
@stubbornella okay to merge :+1: 

The additional commit is usually from this step after merging:

``` shell
npm version minor -m "added Nicole \o/"
git push --tags
git push origin master
```

Nice automated approach to generating a tag.

:shipit:

**Pull request merged**
