### PR TITLE
new gravatar urls format

### PR DESCRIPTION
**Pull request by ashleygwilliams**

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
this is blocking #23

**Comment by aredridel** [comment]
LGTM! The numeric difference is what's breaking the build -- can you fix the test too?

**Comment by ashleygwilliams** [comment]
hehe was just talking with @jefflembeck about that, @aredridel. gonna update it to the number we currently have here in another PR, and then +1 it in #23

**Comment by aredridel** [comment]
Also lgtm with the number fixed in the testr.

**Comment by ashleygwilliams** [comment]
opened test fix in #25

**Comment by ashleygwilliams** [comment]
this is passing now. merge @aredridel @jefflembeck ?

**Comment by aredridel** [comment]
Yep! LGTM!

**Pull request merged**
